### ISSUE TITLE
GZipJson Format to s3

### ISSUE THREAD

**Issue by guptaanamika** [confluentinc/kafka-connect-storage-cloud#115] opened 2017-10-28 18:14 UTC

**Comment by kkonstantine** [comment] 2018-02-12 20:10
Duplicate of: https://github.com/confluentinc/kafka-connect-storage-cloud/issues/120
Resolved with PR: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/98

**Closed by kkonstantine** 2018-02-12 20:10 UTC
Labels: enhancement
