### ISSUE TITLE
unrecoverable  DataException in TimeBasedPartitioner not handled by TombstoneHandler

### ISSUE THREAD

**Issue by teoria** [confluentinc/kafka-connect-storage-cloud#270] opened 2019-09-10 16:54 UTC
cp-kafka-connect:5.2.1

`
{
  "name": "kafka-s3_1",
  "config": {
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "tasks.max": "9",
    "topics": "front",
    "s3.region": "us-east-1",
    "s3.bucket.name": "logs-aggregation",
    "s3.part.size": "5242880",
    "s3.compression.type": "gzip",
    "transforms": "tombstoneHandlerExample",
    "transforms.tombstoneHandlerExample.type": "io.confluent.connect.transforms.TombstoneHandler",
    "transforms.tombstoneHandlerExample.behavior": "warn",
    "flush.size": "60000",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
    "partitioner.class": " io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
    "path.format": "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH",
    "locale": "US",
    "timezone": "UTC",
    "partition.duration.ms": "3600000",
    "timestamp.extractor": "RecordField",
    "timestamp.field": "time_iso8601",
    "schema.compatibility": "NONE",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": "false",
    "name": "kafka-s3_1"
  }
`

A malformed json throw a exception (Unable to find nested field 'time_iso8601') and the TombstoneHandler doesnt work.
i tried with "errors.tolerance":"all"  but no success... :(

 org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
  .at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: The field 'time_iso8601' does not exist in {input={type=log}, agent={hostname=front-2.sss.local, id=03df03af-c92b-4848-a4e1-f9d55394e306, type=filebeat, ephemeral_id=d5824130-581a-4748-9c5d-7d8be74b5b4b, version=8.0.0}, @timestamp=2019-09-05T10:04:07.274Z, ecs={version=1.0.1}, log={file={path=/var/log/nginx/access.log}, offset=7324430099}, @metadata={beat=filebeat, topic=front, type=_doc, version=8.0.0}, host={name=front-2.sss.local}, json={}, message=**{\"request_id\":\"4ce89053f19c2d94571a5c909a4cd8a6\",\"remote_addr\":\"183.122.71.32\",\"remote_user\":\"00010000270003287\",\"time_local\":\"05/Sep/2019:09:38:12 +0000\",\"time_iso8601\":\"2019-09-05T09:38:12+00:00\",\"request\":\"POST /ssss HTTP/1.1\",\"{\"request_id\":\"bcb03b34ba42c278e006d1c7b5ae01ad\",\"remote_addr\":\"189.76.226.78\",\"remote_user\":\"*****-** 01225\",\"time_local\":\"05/Sep/2019:10:04:07 +0000\",\"time_iso8601\":\"2019-09-05T10:04:07+00:00\",\"request\":\"POST /sss HTTP/1.1\",\"status\":\"200\",\"request_length\":350,\"body_bytes_sent\":16,\"server_name\":\"www.ssss.com.br\",\"upstream\":\"upstreamnode\",\"upstream_addr\":\"10.0.1.122:21011\",\"uri\":\"/asd\",\"upstream_response_time\":\"0.004\",\"msec\":1567677847.090,\"request_time\":0.006,\"http_referer\":\"\",\"http_user_agent\":\"\",\"scheme\":\"https\",\"ssl_protocol\":\"TLSv1.2\",\"ssl_cipher\":\"ECDHE-######\",\"hostname\":\"front-2.33333.local\"}**}.
    at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:68)
    at io.confluent.connect.storage.partitioner.TimeBasedPartitioner$RecordFieldTimestampExtractor.extract(TimeBasedPartitioner.java:305)
    at io.confluent.connect.storage.partitioner.TimestampExtractor.extract(TimestampExtractor.java:41)
    at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:198)
    at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:175)
    at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:194)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
    ... 10 more
Caused by: org.apache.kafka.connect.errors.DataException: Unable to find nested field 'time_iso8601'
    at io.confluent.connect.storage.util.DataUtils.getField(DataUtils.java:39)
    at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:63)
    ... 16 more

**Comment by liukrimhrim** [comment] 2019-09-11 21:00
Hi, there! I don't quite see how this is related to TombstoneHandler. TombstoneHandler only filters out records where the entire value field is null. 
As for this error, I think it is due to incorrect field name. Based on my reading of the code, to retrieve field `time_iso8601`, you have to use field name `message.time_iso8601`.
Please let me know if this helps.

**Comment by liukrimhrim** [comment] 2019-09-11 21:02
> cp-kafka-connect:5.2.1
> 
> `{ "name": "kafka-s3_1", "config": { "connector.class": "io.confluent.connect.s3.S3SinkConnector", "tasks.max": "9", "topics": "front", "s3.region": "us-east-1", "s3.bucket.name": "logs-aggregation", "s3.part.size": "5242880", "s3.compression.type": "gzip", "transforms": "tombstoneHandlerExample", "transforms.tombstoneHandlerExample.type": "io.confluent.connect.transforms.TombstoneHandler", "transforms.tombstoneHandlerExample.behavior": "warn", "flush.size": "60000", "storage.class": "io.confluent.connect.s3.storage.S3Storage", "format.class": "io.confluent.connect.s3.format.json.JsonFormat", "partitioner.class": " io.confluent.connect.storage.partitioner.TimeBasedPartitioner", "path.format": "'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH", "locale": "US", "timezone": "UTC", "partition.duration.ms": "3600000", "timestamp.extractor": "RecordField", "timestamp.field": "time_iso8601", "schema.compatibility": "NONE", "value.converter": "org.apache.kafka.connect.json.JsonConverter", "value.converter.schemas.enable": "false", "key.converter": "org.apache.kafka.connect.json.JsonConverter", "key.converter.schemas.enable": "false", "name": "kafka-s3_1" }`
> 
> A malformed json throw a exception (Unable to find nested field 'time_iso8601') and the TombstoneHandler doesnt work.
> i tried with "errors.tolerance":"all" but no success... :(
> 
> org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
> .at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
> at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
> at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.kafka.connect.errors.DataException: The field 'time_iso8601' does not exist in {input={type=log}, agent={hostname=front-2.sss.local, id=03df03af-c92b-4848-a4e1-f9d55394e306, type=filebeat, ephemeral_id=d5824130-581a-4748-9c5d-7d8be74b5b4b, version=8.0.0}, @timestamp=2019-09-05T10:04:07.274Z, ecs={version=1.0.1}, log={file={path=/var/log/nginx/access.log}, offset=7324430099}, @metadata={beat=filebeat, topic=front, type=_doc, version=8.0.0}, host={name=front-2.sss.local}, json={}, message=**{"request_id":"4ce89053f19c2d94571a5c909a4cd8a6","remote_addr":"183.122.71.32","remote_user":"00010000270003287","time_local":"05/Sep/2019:09:38:12 +0000","time_iso8601":"2019-09-05T09:38:12+00:00","request":"POST /ssss HTTP/1.1","{"request_id":"bcb03b34ba42c278e006d1c7b5ae01ad","remote_addr":"189.76.226.78","remote_user":"**_**-** 01225","time_local":"05/Sep/2019:10:04:07 +0000","time_iso8601":"2019-09-05T10:04:07+00:00","request":"POST /sss HTTP/1.1","status":"200","request_length":350,"body_bytes_sent":16,"server_name":"www.ssss.com.br","upstream":"upstreamnode","upstream_addr":"10.0.1.122:21011","uri":"/asd","upstream_response_time":"0.004","msec":1567677847.090,"request_time":0.006,"http_referer":"","http_user_agent":"","scheme":"https","ssl_protocol":"TLSv1.2","ssl_cipher":"ECDHE-######","hostname":"front-2.33333.local"}_*}.
> at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:68)
> at io.confluent.connect.storage.partitioner.TimeBasedPartitioner$RecordFieldTimestampExtractor.extract(TimeBasedPartitioner.java:305)
> at io.confluent.connect.storage.partitioner.TimestampExtractor.extract(TimestampExtractor.java:41)
> at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:198)
> at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:175)
> at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:194)
> at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
> ... 10 more
> Caused by: org.apache.kafka.connect.errors.DataException: Unable to find nested field 'time_iso8601'
> at io.confluent.connect.storage.util.DataUtils.getField(DataUtils.java:39)
> at io.confluent.connect.storage.util.DataUtils.getNestedFieldValue(DataUtils.java:63)
> ... 16 more

Hi, there! I don't quite see how this is related to TombstoneHandler. TombstoneHandler only filters out records where the entire value field is null.
As for this error, I think it is due to incorrect field name. Based on my reading of the code, to retrieve field time_iso8601, you have to use field name message.time_iso8601.
Please let me know if this helps.

**Comment by teoria** [comment] 2019-09-12 00:31
i have a malformed json message. The TimeBasedPartitioner dont find the "timestamp.field" and throw a dataException.  How can i handle this exception ?  "errors.tolerance":"all"  didnt work too.

**Comment by liukrimhrim** [comment] 2019-09-16 15:41
Closing the thread because the problem is irrelevant to TombstoneHandler and `error.tolerance`, and currently we don't support the feature being asked for.

**Closed by liukrimhrim** 2019-09-16 15:41 UTC

**Comment by ZhangSIming-blyq** [comment] 2020-06-03 11:39
Hello, I met the same problem, can you tell me how to ignore the bad record which don't have "nested field 'xxxx'"? thanks

**Comment by radu-almasan** [comment] 2021-06-29 22:57
Was in the same spot; couldn't find a standard, config based solution.

The way I solved it was to create a JAR with custom SMTs. I created one predicate to check for the a field, and a transformer that throws an exception. I then configured the transformer with the predicate so when the field is not there an exception is thrown.

This way the default dead letter forwarding mechanism will happen, as described in the post linked above.

Sample connector config:
```
    "transforms": "assertHasMetaEpoch",
    "transforms.assertHasMetaEpoch.type": "kc.transforms.Asserter",
    "transforms.assertHasMetaEpoch.class": "org.apache.kafka.connect.errors.DataException",
    "transforms.assertHasMetaEpoch.message": "missing meta.epoch field",
    "transforms.assertHasMetaEpoch.predicate": "hasMetaEpochField",
    "transforms.assertHasMetaEpoch.negate": true,

    "predicates": "hasMetaEpochField",
    "predicates.hasMetaEpochField.type": "kc.transforms.predicates.FieldPredicate",
    "predicates.hasMetaEpochField.name": "meta.epoch"
```
