### ISSUE TITLE
Rotate.interval.ms is not commiting

### ISSUE THREAD

**Issue by dimon222** [confluentinc/kafka-connect-storage-cloud#70] opened 2017-07-17 20:44 UTC
I'm using TimeBasedPartitioner for sink to s3, with rotate.interval.ms around 1 minute, and partition.duration.ms around 5 minutes, but I can't anyhow get the full snapshot of data.
I tried to change value flush.size, and I do get more data if I choose the right divisor, but I can't ever get all the data, it seems some stuff is just being stuck in memory till every single partition is filled till flush size, but I don't want that to happen for too long (my data comes in batches on daily basis)

Am I doing it wrong? Is there any another way to force commit/flush ?

**Comment by ewencp** [comment] 2017-07-18 00:08
@dimon222 I think the docs for these options might be a bit confusing (and/or there is a bug). In fact currently only the `rotate.schedule.interval.ms` option checks against the current time (as opposed to the timestamp of the most recent record). Given the current code I think you'd want to use that option instead.

**Comment by dimon222** [comment] 2017-07-18 01:02
@ewencp 
I tried to use rotate.schedule.interval.ms, but I get very strange behavior. If i put interval of 5 minutes, then first 5 minutes of run it will do batch with my specific flush.size. Next 5 minutes are done in flush.size = 1, then it does bulk again for next 5 minutes and etc, till I reach end offset.

Is it expected behavior? Is there any way to force bulk ?
Those 1 record commits are slowing process down significantly.

**Comment by ewencp** [comment] 2017-07-18 05:06
@dimon222 That definitely sounds odd, the `flush.size` should not "reset" like you are seeing. The record count that is tracked is always reset when files are committed.

Do you have any logs from during the two time periods? If you can consistently reproduce the behavior, it's even more helpful if you can turn up the log level -- `INFO` logs provide some insight, but `DEBUG` or even `TRACE` are ideal.

**Comment by dimon222** [comment] 2017-07-18 14:13
@ewencp is there way to drain whole topic?

**Comment by nirajab** [comment] 2017-07-18 16:05
Hey

I have a similar issue. All I am trying to do is take all the data from a given topic and dump it to s3.

The issue I have is the topics are so large that I cannot have flush.size =1 or 3..

If I have a bigger flush size and add the timebased partitioner I am not sure when the data will all be drained to s3. Even after a few attempts it doesnt drain all the topic and it stops when it reaches 

I have close to 150 topics with huge data size and I am trying all different combinations of flush.size , rotate.schedule.interval.ms and partition.duration.ms...

Can you help me ? I am blocked right now because I dont have a way to get all messages froma  topic into S3?

Thanks
Niraja

**Comment by ewencp** [comment] 2017-07-19 00:06
@dimon222 What do you mean by draining the whole topic? Connect will just keep reading from the topic and delivering data indefinitely.

@nirajab The two modes will work in conjunction with each other. `flush.size` should pretty much always be a much larger number, those are just demo values that make it easy in a quickstart to see data being delivered. If you hit `flush.size` records without committing a file, the data will be committed. And every `rotate.schedule.interval.ms`, files will also be committed.

To get all data out of a topic that will no longer have data flowing to it, you'll want to make sure to set `rotate.schedule.interval.ms`, which ensures that it will only take that long before the final data is flushed.

**Comment by nirajampac** [comment] 2017-07-19 00:19
Thanks for the prompt response. I have another question..

We started multiple distributed  workers and we want to run  multiple connectors. But what I seem to see is that only one connector seems to run and the others are stopped when this connector is running.

Is there something we are missing? 

Also when we start any JDBC connectors on the same worked .. the other JDBC connectors are stop started. Is this the way it supposed to work ?

Niraja

**Comment by ewencp** [comment] 2017-07-19 21:32
@nirajab All of them should run. Can you provide any logs or a sequence of steps you are following to reproduce this? Have you check the REST API or logs to see if one of the connectors is misconfigured and it simply crashed?

Regarding restarting, yes, this is expected. Currently the way connect works is that the work the cluster needs to do is [balanced](http://docs.confluent.io/current/connect/concepts.html#task-rebalancing) across the workers. This means that when you add/remove connectors, the amount of work changes and we may need to shift around tasks in order to get the work balanced across the workers.

**Comment by nirajab** [comment] 2017-07-20 15:53
my bad because I was posting new connectors the previous connectors were stopped and the current connector keeps running and thats why I felt its not running in parallel.

I have one last question and hopefully the last.

We were running our connectors on aws spot instances and we lost the box because of price. 
When I started a new box , the sink s3 connectors using Timebased partitioner dumped everything from the topic again into s3 bucket with a different timestamp. The source Jdbc connector didnt retrieve everything .. how can I make the sink s3 connector remember the last offset incase of crashes.

N

**Comment by ewencp** [comment] 2017-07-20 21:16
@nirajab It should commit offsets periodically, so it should not replay the entire topic. There was a bug which just got fixed in #72 but it would have only redelivered one extra message in that case, not the entire topic. If you have logs, we can see whether offset commits are being attempted or not.

**Comment by nirajampac** [comment] 2017-07-20 21:27
Sorry killed my spot instance ... so don't have logs

**Comment by briggsw** [comment] 2017-07-27 20:59
@dimon222 I am seeing very similar behavior to you; my s3 connectors don't seem to be committing offsets, and occasionally, they will go haywire and flush a file for every single record. I just posted on the Confluent Platform mailing list about the issue.

**Comment by kkonstantine** [comment] 2017-07-28 17:32
We have merged a fix (https://github.com/confluentinc/kafka-connect-storage-cloud/pull/72) that seems to address the symptoms that are described with offset commit and small file generation. 

The fix will appear soon in the next release of the connector (`3.3.0`) and will also be available in future bug fix releases of 3.2.x (that is `x > 2`). In the meantime it is available to you if you can build and use the repo's source code.

**Comment by briggsw** [comment] 2017-07-28 18:29
Thanks @kkonstantine - I had been using a home-built 3.2.x prior to the 3.2.2 release for some other fixes, then abandoned it when 3.2.2 was released - I will switch back to using the current 3.2.x and see how that works.

**Comment by kkonstantine** [comment] 2017-07-28 18:39
Sounds good. Also, feel free to share if you want the reasons behind the fixes you had to apply on your own to improve your connectors functionality, or even better submit PRs with those fixes if you think they'll be useful to others as well.

**Comment by briggsw** [comment] 2017-07-28 19:21
The fixes weren't home-brewed fixes, just fixes that weren't in 3.2.1 but were released as part of 3.2.2... I'm pretty sure it was related to the TimeBasedPartitioner, but my memory isn't what it used to be...

**Comment by dimon222** [comment] 2017-08-01 20:13
@kkonstantine 
I confirm that the fix that was applied in that merge does actually resolve the issue for me.
Unfortunately, I wasn't able to build stuff from 3.2.x branch as is via "mvn package" (dependency problems) so I had to apply the patch manually to tag 3.2.2.

There are still small files sometimes appearing, but they're true files (basically the last stage of push, when rotate interval was reached before filling the flush.size completely).

**Closed** 2017-08-03 16:06 UTC
Labels: question
