### ISSUE TITLE
unable to use aws credentials with sts profile locally

### ISSUE THREAD

**Issue by bagipriyank** [confluentinc/kafka-connect-storage-cloud#298] opened 2020-01-16 21:50 UTC
I am running kafka locally on my mac via 
```
zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties & kafka-server-start /usr/local/etc/kafka/server.properties
```

and then trying to run kafka s3 connect by invoking 
```
connect-standalone /etc/kafka-worker.properties /etc/kafka-connect-s3/s3-sink.properties
```

Also, i had copied `aws-java-sdk-core-1.11.86.jar` and `aws-java-sdk-sts-1.11.86.jar` along with the jar containing compiled protobuf class to `/usr/local/Cellar/kafka/2.3.1/libexec/libs`

kafka-worker.properties
```
bootstrap.servers = localhost:9092
key.converter = org.apache.kafka.connect.storage.StringConverter
value.converter = com.blueapron.connect.protobuf.ProtobufConverter
value.converter.protoClassName = com.bagi.protobuf.TrackingEvent$Event
plugin.path = /usr/local/share/java/
offset.storage.file.filename = /etc/kafka-offsets
```

s3-sink.properties
```
name=s3-sink
connector.class=io.confluent.connect.s3.S3SinkConnector
tasks.max=1
topics=PLAY

s3.region=us-east-1
s3.bucket.name=dev-bagi
s3.credentials.provider.class=com.amazonaws.auth.profile.ProfileCredentialsProvider
s3.part.size=5242880
flush.size=3

storage.class=io.confluent.connect.s3.storage.S3Storage
format.class=io.confluent.connect.s3.format.parquet.ParquetFormat
partitioner.class=io.confluent.connect.storage.partitioner.DefaultPartitioner

schema.compatibility=NONE
```

and i get following stack trace in the logs
```
[2020-01-16 13:32:07,261] ERROR WorkerSinkTask{id=s3-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
java.lang.ClassCastException: com.amazonaws.services.securitytoken.internal.STSProfileCredentialsService cannot be cast to com.amazonaws.auth.profile.internal.securitytoken.ProfileCredentialsService
	at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getProfileCredentialService(STSProfileCredentialsServiceProvider.java:54)
	at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getProfileCredentialsProvider(STSProfileCredentialsServiceProvider.java:38)
	at com.amazonaws.auth.profile.internal.securitytoken.STSProfileCredentialsServiceProvider.getCredentials(STSProfileCredentialsServiceProvider.java:71)
	at com.amazonaws.auth.profile.internal.ProfileAssumeRoleCredentialsProvider.getCredentials(ProfileAssumeRoleCredentialsProvider.java:51)
	at com.amazonaws.auth.profile.ProfilesConfigFile.getCredentials(ProfilesConfigFile.java:162)
	at com.amazonaws.auth.profile.ProfileCredentialsProvider.getCredentials(ProfileCredentialsProvider.java:161)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1115)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:728)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1302)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1259)
	at io.confluent.connect.s3.storage.S3Storage.bucketExists(S3Storage.java:169)
	at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:108)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is what my aws credentials file looks like
```
[default]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/MyProfile
source_profile = my-profile

[my-profile]
aws_access_key_id=AAAAA
aws_secret_access_key=BBBBB
aws_session_token=CCCCC
```

**Comment by bagipriyank** [comment] 2020-01-16 23:12
I even tried using https://github.com/Nordstrom/kafka-connect-assume-role and that didn't work either. Ended up filing https://github.com/Nordstrom/kafka-connect-assume-role/issues/2.

**Comment by bagipriyank** [comment] 2020-01-18 01:30
this problem happens with kafka-connect-s3-5.4.0.jar which was installed by invoking 
```
confluent-hub install confluentinc/kafka-connect-s3:latest --verbose --component-dir /usr/share/java/ --worker-configs /etc/kafka-worker.properties
```
the issue didn't occur on using a jar build from tip of master i.e. kafka-connect-s3-5.5.0-SNAPSHOT.jar

**Comment by bagipriyank** [comment] 2020-01-18 01:57
i'm unable to reproduce it now so closing.

**Comment by bagipriyank** [comment] 2020-01-21 18:23
had forgotten to unset env variables with keys from a poc which made it work for build from tip of master. the issue still persists.

**Comment by cricket007** [comment] 2020-01-27 14:41
Any reason to use Homebrew kafka instead of Confluent Platform?

**Comment by bagipriyank** [comment] 2020-01-27 15:46
No particular reason for using homebrew Kafka. I had to copy those two jars because I got an error about missing class when using `s3.credentials.provider.class=com.amazonaws.auth.profile.ProfileCredentialsProvider` without them which went away with these specific jars.

**Comment by cricket007** [comment] 2020-01-27 15:54
Sure, but as I said, S3 Connect includes them in its own lib folder

**Comment by bagipriyank** [comment] 2020-01-27 18:13
```
C02TW0TMHTDG:~ pbagrecha$ ls -lh /usr/local/share/java/confluentinc-kafka-connect-s3/lib/
total 103128
-rw-r--r--  1 pbagrecha  admin    44K Jan 25 15:42 apacheds-i18n-2.0.0-M15.jar
-rw-r--r--  1 pbagrecha  admin   675K Jan 25 15:42 apacheds-kerberos-codec-2.0.0-M15.jar
-rw-r--r--  1 pbagrecha  admin    16K Jan 25 15:42 api-asn1-api-1.0.0-M20.jar
-rw-r--r--  1 pbagrecha  admin    78K Jan 25 15:42 api-util-1.0.0-M20.jar
-rw-r--r--  1 pbagrecha  admin    42K Jan 25 15:42 asm-3.1.jar
-rw-r--r--  1 pbagrecha  admin    20K Jan 25 15:42 audience-annotations-0.5.0.jar
-rw-r--r--  1 pbagrecha  admin   554K Jan 25 15:42 avro-1.9.1.jar
-rw-r--r--  1 pbagrecha  admin   756K Jan 25 15:42 aws-java-sdk-core-1.11.86.jar
-rw-r--r--  1 pbagrecha  admin   435K Jan 25 15:42 aws-java-sdk-kms-1.11.86.jar
-rw-r--r--  1 pbagrecha  admin   745K Jan 25 15:42 aws-java-sdk-s3-1.11.86.jar
-rw-r--r--  1 pbagrecha  admin    23K Jan 25 15:42 common-config-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin    17K Jan 25 15:42 common-utils-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin   241K Jan 25 15:42 commons-beanutils-1.9.4.jar
-rw-r--r--  1 pbagrecha  admin    40K Jan 25 15:42 commons-cli-1.2.jar
-rw-r--r--  1 pbagrecha  admin    57K Jan 25 15:42 commons-codec-1.4.jar
-rw-r--r--  1 pbagrecha  admin   575K Jan 25 15:42 commons-collections-3.2.2.jar
-rw-r--r--  1 pbagrecha  admin   236K Jan 25 15:42 commons-compress-1.4.1.jar
-rw-r--r--  1 pbagrecha  admin   292K Jan 25 15:42 commons-configuration-1.6.jar
-rw-r--r--  1 pbagrecha  admin   140K Jan 25 15:42 commons-digester-1.8.jar
-rw-r--r--  1 pbagrecha  admin   298K Jan 25 15:42 commons-httpclient-3.1.jar
-rw-r--r--  1 pbagrecha  admin   181K Jan 25 15:42 commons-io-2.4.jar
-rw-r--r--  1 pbagrecha  admin   278K Jan 25 15:42 commons-lang-2.6.jar
-rw-r--r--  1 pbagrecha  admin   376K Jan 25 15:42 commons-lang3-3.2.1.jar
-rw-r--r--  1 pbagrecha  admin    61K Jan 25 15:42 commons-logging-1.1.3.jar
-rw-r--r--  1 pbagrecha  admin   1.5M Jan 25 15:42 commons-math3-3.1.1.jar
-rw-r--r--  1 pbagrecha  admin   267K Jan 25 15:42 commons-net-3.1.jar
-rw-r--r--  1 pbagrecha  admin   109K Jan 25 15:42 commons-pool-1.6.jar
-rw-r--r--  1 pbagrecha  admin    68K Jan 25 15:42 curator-client-2.7.1.jar
-rw-r--r--  1 pbagrecha  admin   182K Jan 25 15:42 curator-framework-2.7.1.jar
-rw-r--r--  1 pbagrecha  admin   264K Jan 25 15:42 curator-recipes-2.7.1.jar
-rw-r--r--  1 pbagrecha  admin    17M Jan 25 15:42 fastutil-7.0.13.jar
-rw-r--r--  1 pbagrecha  admin   236K Jan 25 15:42 gson-2.8.5.jar
-rw-r--r--  1 pbagrecha  admin   1.6M Jan 25 15:42 guava-11.0.2.jar
-rw-r--r--  1 pbagrecha  admin    40K Jan 25 15:42 hadoop-annotations-2.7.7.jar
-rw-r--r--  1 pbagrecha  admin    92K Jan 25 15:42 hadoop-auth-2.7.7.jar
-rw-r--r--  1 pbagrecha  admin   3.3M Jan 25 15:42 hadoop-common-2.7.7.jar
-rw-r--r--  1 pbagrecha  admin   719K Jan 25 15:42 httpclient-4.5.2.jar
-rw-r--r--  1 pbagrecha  admin   319K Jan 25 15:42 httpcore-4.4.4.jar
-rw-r--r--  1 pbagrecha  admin   551K Jan 25 15:42 ion-java-1.0.1.jar
-rw-r--r--  1 pbagrecha  admin    65K Jan 25 15:42 jackson-annotations-2.9.10.jar
-rw-r--r--  1 pbagrecha  admin   318K Jan 25 15:42 jackson-core-2.9.10.jar
-rw-r--r--  1 pbagrecha  admin   227K Jan 25 15:42 jackson-core-asl-1.9.13.jar
-rw-r--r--  1 pbagrecha  admin   1.3M Jan 25 15:42 jackson-databind-2.9.10.1.jar
-rw-r--r--  1 pbagrecha  admin    50K Jan 25 15:42 jackson-dataformat-cbor-2.9.10.jar
-rw-r--r--  1 pbagrecha  admin    41K Jan 25 15:42 jackson-dataformat-yaml-2.9.10.jar
-rw-r--r--  1 pbagrecha  admin    69K Jan 25 15:42 jackson-datatype-joda-2.9.10.jar
-rw-r--r--  1 pbagrecha  admin    17K Jan 25 15:42 jackson-jaxrs-1.8.3.jar
-rw-r--r--  1 pbagrecha  admin   762K Jan 25 15:42 jackson-mapper-asl-1.9.13.jar
-rw-r--r--  1 pbagrecha  admin    32K Jan 25 15:42 jackson-xc-1.8.3.jar
-rw-r--r--  1 pbagrecha  admin    18K Jan 25 15:42 java-xmlbuilder-0.4.jar
-rw-r--r--  1 pbagrecha  admin   123K Jan 25 15:42 jaxb-api-2.3.0.jar
-rw-r--r--  1 pbagrecha  admin   869K Jan 25 15:42 jaxb-impl-2.2.3-1.jar
-rw-r--r--  1 pbagrecha  admin   448K Jan 25 15:42 jersey-core-1.9.jar
-rw-r--r--  1 pbagrecha  admin   144K Jan 25 15:42 jersey-json-1.9.jar
-rw-r--r--  1 pbagrecha  admin   696K Jan 25 15:42 jersey-server-1.9.jar
-rw-r--r--  1 pbagrecha  admin   527K Jan 25 15:42 jets3t-0.9.0.jar
-rw-r--r--  1 pbagrecha  admin    66K Jan 25 15:42 jettison-1.1.jar
-rw-r--r--  1 pbagrecha  admin   527K Jan 25 15:42 jetty-6.1.26.jar
-rw-r--r--  1 pbagrecha  admin    18K Jan 25 15:42 jetty-sslengine-6.1.26.jar
-rw-r--r--  1 pbagrecha  admin   209K Jan 25 15:42 jline-2.12.1.jar
-rw-r--r--  1 pbagrecha  admin    26K Jan 25 15:42 jmespath-java-1.11.86.jar
-rw-r--r--  1 pbagrecha  admin   617K Jan 25 15:42 joda-time-2.9.6.jar
-rw-r--r--  1 pbagrecha  admin   274K Jan 25 15:42 jsch-0.1.54.jar
-rw-r--r--  1 pbagrecha  admin    98K Jan 25 15:42 jsp-api-2.1.jar
-rw-r--r--  1 pbagrecha  admin    32K Jan 25 15:42 jsr305-3.0.0.jar
-rw-r--r--  1 pbagrecha  admin    38K Jan 25 15:42 kafka-avro-serializer-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin    46K Jan 25 15:42 kafka-connect-avro-converter-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin    81K Jan 25 15:42 kafka-connect-s3-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin   7.5K Jan 25 15:42 kafka-connect-storage-common-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin    28K Jan 25 15:42 kafka-connect-storage-core-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin   4.3K Jan 25 15:42 kafka-connect-storage-format-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin    26K Jan 25 15:42 kafka-connect-storage-partitioner-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin    74K Jan 25 15:42 kafka-schema-registry-client-5.4.0.jar
-rw-r--r--  1 pbagrecha  admin   478K Jan 25 15:42 log4j-1.2.17.jar
-rw-r--r--  1 pbagrecha  admin   271K Jan 25 15:42 netty-buffer-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin   311K Jan 25 15:42 netty-codec-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin   590K Jan 25 15:42 netty-common-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin   427K Jan 25 15:42 netty-handler-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin    32K Jan 25 15:42 netty-resolver-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin   462K Jan 25 15:42 netty-transport-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin   121K Jan 25 15:42 netty-transport-native-epoll-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin    32K Jan 25 15:42 netty-transport-native-unix-common-4.1.42.Final.jar
-rw-r--r--  1 pbagrecha  admin   123K Jan 25 15:42 parquet-avro-1.10.1.jar
-rw-r--r--  1 pbagrecha  admin   1.0M Jan 25 15:42 parquet-column-1.10.1.jar
-rw-r--r--  1 pbagrecha  admin    93K Jan 25 15:42 parquet-common-1.10.1.jar
-rw-r--r--  1 pbagrecha  admin   829K Jan 25 15:42 parquet-encoding-1.10.1.jar
-rw-r--r--  1 pbagrecha  admin   706K Jan 25 15:42 parquet-format-2.4.0.jar
-rw-r--r--  1 pbagrecha  admin   279K Jan 25 15:42 parquet-hadoop-1.10.1.jar
-rw-r--r--  1 pbagrecha  admin   1.0M Jan 25 15:42 parquet-jackson-1.10.1.jar
-rw-r--r--  1 pbagrecha  admin   521K Jan 25 15:42 protobuf-java-2.5.0.jar
-rw-r--r--  1 pbagrecha  admin   103K Jan 25 15:42 servlet-api-2.5.jar
-rw-r--r--  1 pbagrecha  admin    40K Jan 25 15:42 slf4j-api-1.7.26.jar
-rw-r--r--  1 pbagrecha  admin    12K Jan 25 15:42 slf4j-log4j12-1.7.26.jar
-rw-r--r--  1 pbagrecha  admin   294K Jan 25 15:42 snakeyaml-1.23.jar
-rw-r--r--  1 pbagrecha  admin   1.0M Jan 25 15:42 snappy-java-1.1.2.6.jar
-rw-r--r--  1 pbagrecha  admin    21K Jan 25 15:42 swagger-annotations-1.5.22.jar
-rw-r--r--  1 pbagrecha  admin    72K Jan 25 15:42 swagger-core-1.5.3.jar
-rw-r--r--  1 pbagrecha  admin   119K Jan 25 15:42 swagger-models-1.5.3.jar
-rw-r--r--  1 pbagrecha  admin    15K Jan 25 15:42 xmlenc-0.52.jar
-rw-r--r--  1 pbagrecha  admin    92K Jan 25 15:42 xz-1.0.jar
-rw-r--r--  1 pbagrecha  admin   962K Jan 25 15:42 zookeeper-3.5.6.jar
-rw-r--r--  1 pbagrecha  admin   244K Jan 25 15:42 zookeeper-jute-3.5.6.jar
```

I didn't need to copy `aws-java-sdk-core-1.11.86.jar` but it is missing `aws-java-sdk-sts-1.11.86.jar`

**Comment by cricket007** [comment] 2020-01-27 18:16
AFAIK, ProfileCredentialsProvider is part of core

**Comment by cricket007** [comment] 2020-01-27 18:18
I think the issue is the use of `aws_session_token`. Plus, if you run Connect on bare EC2, it should just accept the instance profile metadata IAM, so you wouldn't need the AWS config file

**Comment by bagipriyank** [comment] 2020-01-27 18:20
completely agree to both of your comments :)

**Comment by cricket007** [comment] 2020-01-27 18:25
👍 Feel free to create a PR adding `sts` as a maven dependency if you think it is useful for others

**Comment by bagipriyank** [comment] 2020-01-27 20:39
will do once i figure out how to get it to work.

**Comment by kkonstantine** [comment] 2020-03-09 22:59
This should now be fixed by: https://github.com/confluentinc/kafka-connect-storage-cloud/pull/311

Please open an issue with this provider and in the current repo if it doesn't cover your use case.

**Closed by kkonstantine** 2020-03-09 22:59 UTC

**Comment by bagipriyank** [comment] 2020-03-15 07:56
This works even with `com.amazonaws.auth.DefaultAWSCredentialsProviderChain` now that aws client version has been upgraded to 1.11.725
