### ISSUE TITLE
Where can I find documentation on all the s3 connector options?

### ISSUE THREAD

**Issue by DaveSlinn** [confluentinc/kafka-connect-storage-cloud#236] opened 2019-03-21 20:39 UTC
This page https://docs.confluent.io/current/connect/kafka-connect-s3/configuration_options.html doesn't describe the topics.regex property and I can't seem to find anything relevant to it.

Is there additional documentation for this property (and others?)

**Comment by n-kyriakopoulos** [comment] 2019-03-28 17:27
I'd hazard a guess that topics.regex is a "default config" among confluent connectors. Their docs are on the sparse side but try [Confluent's config page.](https://docs.confluent.io/3.1.2/connect/connect-replicator/docs/configuration_options.html)

**Comment by kkonstantine** [comment] 2019-03-28 18:55
Not imported in the connector docs because it's a framework property provided in all sink connectors. 
Some info here: https://kafka.apache.org/documentation/#sinkconnectconfigs

Keeping this ticket open until we update the doc generators to pull this config (and any similar) in to the connector config options.

**Comment by DaveSlinn** [comment] 2019-03-28 18:57
Thanks for point out the kafka docs.  Didn't even think to look there.  I'm still pretty new to this stuff, and still trying to nail down the line between Apache Kafka and Confluent.

**Comment by aakashnshah** [comment] 2020-01-10 00:31
@DaveSlinn looks like the issue is resolved, so I will go ahead and close the issue.

**Closed by aakashnshah** 2020-01-10 00:31 UTC
