### ISSUE TITLE
Getting NullPointerException when using rotate.interval.ms

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-storage-cloud#109] opened 2017-10-20 23:43 UTC
I just upgraded to 3.3.0 and I'm trying out the new `rotate.interval.ms config`. I'm seeing the following exception when using it on my S3 connectors:

```
[2017-10-20 23:21:35,233] ERROR Task foo-to-S3-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.NullPointerException
        at io.confluent.connect.s3.TopicPartitionWriter.rotateOnTime(TopicPartitionWriter.java:288)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:234)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:464)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:265)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
[2017-10-20 23:21:35,233] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2017-10-20 23:21:35,233] ERROR Task foo-to-S3-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:484)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:265)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

The stack trace is pointing to this line: https://github.com/confluentinc/kafka-connect-storage-cloud/blob/v3.3.0/kafka-connect-s3/src/main/java/io/confluent/connect/s3/TopicPartitionWriter.java#L288

My debugging so far has revealed that the `recordTimestamp` field is null. I'm still debugging, but I wanted to create an issue to track the problem and see if it's a known issue or if there's an obvious solution.

**Comment by zzbennett** [comment] 2017-10-21 00:01
It looks like the `rotate.interval.ms` will only work with the TimeBasedPartitioner given the way it is currently implemented. Is this intended? Or a bug?

**Comment by kkonstantine** [comment] 2017-10-27 21:05
By design. `rotate.interval.ms` can be based on timestamp if the partitioner is not based on wallclock. We'll need to update the docs to reflect this requirement specifically. 

NPE there is something we also want to improve by throwing an intuitive error message. 

`rotate.schedule.interval.ms` however is independent of partitioner. (You might see duplicates too though if you used it).

**Comment by zzbennett** [comment] 2017-10-27 21:22
Okay, thanks @kkonstantine. I'm still wondering why `rotate.interval.ms` cannot be used with any partitioner besides the TimeBasedPartitioner. The way it is described in the docs suggests that it will use wallclock time to flush at regular intervals. But actually, given the way it is implemented, it will get the time from the events themselves (depending on how the timestamp extractor is configured). It seems to me that it shouldn't matter what partitioner I'm using. If I configure `rotate.interval.ms` to be 30 seconds, it will flush every 30 seconds, so long as there is data in the buffer. Was there a specific reason it doesn't work like this? Or could it be modified to support this functionality?

**Comment by zzbennett** [comment] 2017-10-27 21:34
A fix like this is basically all I'd need: https://github.com/zzbennett/kafka-connect-storage-cloud/commit/64e3d1ecec5b110528f6de59b8351c7ac0cc0adc If there is no TimestampExtractor defined, just default to wall clock.

**Comment by kkonstantine** [comment] 2017-10-27 21:42
Yes, this is central in the design of the S3 connector. 

We strived to make the connector have exactly-once semantics on top of an eventual consistent store such as S3 without depending on any external dependency (consistent stores etc) besides Kafka and S3. 

This can not happen when wall-clock is used for partitioning. Still wall-clock is the default for time-based partitioning and can be used along with size-based partitioning. 

There are enhancements to be made probably in terms of partitioning options, but the current state machine of the connector seems to cover a wide range of use cases, many of which might need a custom partitioner.  Would you like to mention what are your partitioning requirements that are not covered by the current configuration options?

**Comment by zzbennett** [comment] 2017-10-27 22:20
Sure. So we are basically using time based partitioning, but our custom partitioner actually makes a call to a service that we built to get the partition info. This service handles creating the tables and partitions in hive, among a few other things.

It's not the best architecture, more just tech debt from our legacy logging infrastructure that we've had to go with for the time being.

I think I understand what you're saying now about the exactly-once semantics and the time based flushing. The timestamp is read from the event in order to achieve exactly-once semantics but also to be able to flush on regular intervals.

In this case, I could use `rotate.schedule.interval.ms` and set the interval to like 30 seconds. So long as the size base flushing will take precedence, which, from looking at the code, looks like will happen, i.e. if the buffer fills up in 5 seconds, it will still flush to S3, even though the interval is set to 30 seconds. I will still run into the same NPE for now, since it gets thrown before the rotate schedule interval logic is reached in the `rotateOnTime` method, but that's an easy fix.

**Comment by zzbennett** [comment] 2017-11-09 00:36
Actually, I just confirmed that the NPE does not happen when using `rotate.schedule.interval.ms` because of a short circuit in boolean logic, so that's good.

I'd be happy to add some logic to prevent the NPE from happening at all. I'm wondering what the best solution is. I'm thinking of doing either:
1) Add some validation logic directly in the `TopicPartitionWriter` itself to ensure `rotate.interval.ms` is not used with anything other than the `TimeBasedPartitioner`. 
2) Add the validation logic in `S3SinkConnectorConfig` so that the issue is caught in the validate step.
3) Add the logic to `io.confluent.connect.storage.partitioner.PartitionerConfig`. That's where the configs are actually defined so it seems sensible, but then any connector using the `PartitionerConfig` class gets the same validation, which is maybe not desirable.

**Comment by sanjaypsmc** [comment] 2017-12-29 19:37
Just ran into this myself. It would be very useful to have this dependency documented in https://docs.confluent.io/current/connect/connect-storage-cloud/kafka-connect-s3/docs/configuration_options.html#s3-configuration-options.

**Comment by kkonstantine** [comment] 2018-02-02 22:39
The following PRs seem to have fixed the issues described here: 

https://github.com/confluentinc/kafka-connect-storage-common/pull/55
https://github.com/confluentinc/kafka-connect-storage-cloud/pull/136
https://github.com/confluentinc/kafka-connect-storage-cloud/pull/138

**Comment by kkonstantine** [comment] 2018-02-02 22:41
I'll go ahead and close this issue, but feel free to re-open if I missed a case where NPE would be thrown either due to misconfiguration or due to records without timestamp with timestamp extractors that depend on it.

**Closed by kkonstantine** 2018-02-02 22:41 UTC

**Comment by zzbennett** [comment] 2018-02-09 02:05
Thanks @kkonstantine I think that does fix it.

**Comment by ssbiox** [comment] 2018-04-09 03:50
@kkonstantine I would like to use FieldPartitioner with the ability to flush by size or time interval, whichever happens first. I got the same NullPointerException, but learned from comments that I have to use flush.size and rotate.schedule.interval.ms. Could you please provide more details why duplicates may occur on restart, so I could think of any workaround or custom partitioner implementation that guarantees exactly-once semantics?

**Comment by kkonstantine** [comment] 2018-04-10 20:39
@ssbiox at a high level, if you partitioning is deterministic, e.g. it relies on the kafka timestamps or a record field that stores a timestamp for a record, you shouldn't see duplicates. If, however, your partitioning is not deterministic, because for instance it depends on wall clock time, then you might see duplicates occasionally.
