### ISSUE TITLE
S3 Connector throws AvroRuntimeException

### ISSUE THREAD

**Issue by TT-vJanardhanan** [confluentinc/kafka-connect-storage-cloud#185] opened 2018-07-11 21:24 UTC
I have the below configuration for the s3 connector.
```
 {
   "name": "s3-sink",
   "config": {
     "connector.class": "io.confluent.connect.s3.S3SinkConnector",
     "tasks.max": "5",
     "topics": "s3-topic",
     "s3.region": "us-east-1",
     "s3.bucket.name": "bucket-name",
     "s3.part.size": "5242880",
     "flush.size": "500",
     "storage.class": "io.confluent.connect.s3.storage.S3Storage",
     "format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
     "schema.generator.class": "io.confluent.connect.storage.hive.schema.TimeBasedSchemaGenerator",
     "name": "s3-sink",
     "partition.duration.ms":600000,
     "rotate.interval.ms": 86400000,
     "key.converter": "org.apache.kafka.connect.storage.StringConverter",
     "value.converter": "org.apache.kafka.connect.json.JsonConverter",
     "value.converter.schemas.enable": "false",
     "partitioner.class":"io.confluent.connect.storage.partitioner.TimeBasedPartitioner",
     "path.format":"'year'=YYYY/'month'=MM/'day'=dd/'hour'=HH",
     "locale": "en",
     "timestamp.extractor": "Record",
     "timezone": "UTC"
   }
 }
```

It works as expected when the flush size=1 where it dumps each record into a separate avro file.
But on increasing the flush size to any other value, it tries to open the same file multiple times, which ends up in error: "**Caused by: org.apache.avro.AvroRuntimeException: already open**"

Sample logs:
```
[2018-07-11 14:02:01,364] INFO Opening record writer for: topics/s3-topic/year=2018/month=07/day=11/hour=19/s3-topic+8+0000000000.avro (io.confluent.connect.s3.format.avro.AvroRecordWriterProvider:68)
[2018-07-11 14:02:01,366] INFO Opening record writer for: topics/s3-topic/year=2018/month=07/day=11/hour=19/s3-topic+3+0000000000.avro (io.confluent.connect.s3.format.avro.AvroRecordWriterProvider:68)
[2018-07-11 14:02:01,368] INFO Opening record writer for: topics/s3-topic/year=2018/month=07/day=11/hour=19/s3-topic+3+0000000000.avro (io.confluent.connect.s3.format.avro.AvroRecordWriterProvider:68)
[2018-07-11 14:02:01,368] ERROR WorkerSinkTask{id=s3-sink-3} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:544)
org.apache.avro.AvroRuntimeException: already open
        at org.apache.avro.file.DataFileWriter.assertNotOpen(DataFileWriter.java:85)
        at org.apache.avro.file.DataFileWriter.setCodec(DataFileWriter.java:93)
        at io.confluent.connect.s3.format.avro.AvroRecordWriterProvider$1.write(AvroRecordWriterProvider.java:71)
        at io.confluent.connect.s3.TopicPartitionWriter.writeRecord(TopicPartitionWriter.java:477)
        at io.confluent.connect.s3.TopicPartitionWriter.checkRotationOrAppend(TopicPartitionWriter.java:267)
        at io.confluent.connect.s3.TopicPartitionWriter.executeState(TopicPartitionWriter.java:212)
        at io.confluent.connect.s3.TopicPartitionWriter.write(TopicPartitionWriter.java:176)
        at io.confluent.connect.s3.S3SinkTask.put(S3SinkTask.java:195)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:524)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:302)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Anything wrong with my configuration or is this a bug?

**Comment by samdjstephens** [comment] 2018-08-09 16:33
Same issue. My config:
```json
{
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "flush.size": "32",
    "format.class": "io.confluent.connect.s3.format.avro.AvroFormat",
    "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
    "key.converter.schemas.enable": "false",
    "name": "test-avro-s3-sink-2",
    "partitioner.class": "io.confluent.connect.storage.partitioner.DefaultPartitioner",
    "s3.bucket.name": "temp-bucket-kafka-connect",
    "s3.region": "eu-west-1",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "tasks.max": "1",
    "topics": "test-topic-a",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false"
}
```

As an observation, it seems that we both have `JsonConverter` as the value converter. I wonder if the issue is related to the inferred schema of the messages, mainly because for another connector I have deployed where the topic messages are Avro (and where I'm more confident the messages have a consistent schema), I don't get the same issue.

Theres a similar issue against [kafka-connect-hdfs](https://github.com/confluentinc/kafka-connect-hdfs/issues/298)

**Comment by kkonstantine** [comment] 2018-09-18 21:16
As observed, `JsonConverter` is compatible with `io.confluent.connect.s3.format.json.JsonFormat` and `AvroConverter` is compatible with `io.confluent.connect.s3.format.avro.AvroFormat`. 

Closing this ticket, since it's a result of misconfiguration.

**Closed by kkonstantine** 2018-09-18 21:16 UTC

**Comment by samdjstephens** [comment] 2018-09-18 21:54
@kkonstantine My understanding was that the value converter was for deserialising messages off the topic (in to Connect’s internal data format) and the format configuration is the class used for serialising the data for output. If this is true then it seems like the converter and format have been coupled in a way that at the very least should be clearly documented or better refused by the S3 connector as invalid configuration.

**Comment by cgiraldo** [comment] 2019-08-29 08:10
as @samdjstephens says, I think this is not a misconfiguration and the issue should be reopen.

It is well explained [here](https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained#json-topics)

> The format in which you’re reading data from a source, or writing it to an external data store, doesn’t need to have a bearing on the format you use to serialize your messages in Kafka.

**Comment by ifastva** [comment] 2019-12-05 13:37
any update on this ?

**Comment by ThomasBorghs** [comment] 2020-06-12 09:33
> as @samdjstephens says, I think this is not a misconfiguration and the issue should be reopen.
> 
> It is well explained [here](https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained#json-topics)
> 
> > The format in which you’re reading data from a source, or writing it to an external data store, doesn’t need to have a bearing on the format you use to serialize your messages in Kafka.

I would indeed assume (given the quoted article) that reading from a JSON encoded topic, and serializing to AVRO would be possible. And that the given configuration would be correct for such a setup.

I'm trying to run a similar setup, so conclusion is that this is impossible using the connector?

**Comment by bradurani** [comment] 2020-11-06 06:40
Has anyone found solution for this? I'm stuck in it too

**Comment by peay** [comment] 2020-11-26 12:00
Hitting this as well (and as indicated in https://github.com/confluentinc/kafka-connect-hdfs/issues/298, it works if flush.size == 1 and fails otherwise), any thoughts @kkonstantine?

**Comment by bradurani** [comment] 2020-11-30 17:49
I was able to confirm that it is indeed a problem caused by using schema-less JSON with an Avro formatter. I was able to work around this issue by creating an SMT that changes the value from a `HashMap` to a `Struct` and supplies a `Schema` object.
